# Generated by Django 3.0.4 on 2020-04-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
