# Generated by Django 3.0.4 on 2020-05-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20200506_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
