# Generated by Django 3.0.4 on 2020-05-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order1',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product1',
        ),
    ]
