# Generated by Django 3.0.4 on 2020-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20200506_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order1',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price1',
        ),
    ]
